### ISSUE TITLE
Alert helper can't compile in Swift?

### ISSUE THREAD

**Issue by brockboland** [vokal/VOKUtilities#3]
> ClientName/Pods/VOKUtilities/Pod/VOKAlertHelper/VOKAlertHelper.h:11:9: 'VOKAlertAction.h' file not found with <angled> include; use "quotes" instead

**Comment by vokal-isaac** [comment]
I think you were using `#import "VOKAlertHelper.h"` when maybe `#import <VOKAlertHelper.h>` would have worked?

**Comment by brockboland** [comment]
Other way round: it's using angle brackets now, and the compiler was suggesting quotes. This is the line in question:

https://github.com/vokal/VOKUtilities/blob/master/Pod/VOKAlertHelper/VOKAlertHelper.h#L11

**Comment by vokal-isaac** [comment]
Ahh, in that case, it's probably the path thing.  Try `#import <VOKUtilities/VOKAlertHelper.h>` (or something like that).

**Comment by vokal-isaac** [comment]
Er... maybe not, if it's inside... given that it's inside the pod, it should be quotes, I think.

**Comment by bryanluby** [comment]
Closing as current implementation works as expected.
